-- Flyway migration script V1: Initial schema for wallet service
-- Compatible with H2 and PostgreSQL

CREATE TABLE wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(255) NOT NULL UNIQUE,
    owner_name VARCHAR(255) NOT NULL,
    balance DECIMAL(19,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    amount DECIMAL(19,2) NOT NULL,
    type VARCHAR(50) NOT NULL,
    transaction_date TIMESTAMP,
    CONSTRAINT fk_transaction_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(id) ON DELETE CASCADE
);

-- Index for faster queries on wallet_id
CREATE INDEX idx_transactions_wallet_id ON transactions(wallet_id);

-- Optional: Index for account_number lookup
CREATE INDEX idx_wallets_account_number ON wallets(account_number);

-- Optional: Index for soft delete filtering
CREATE INDEX idx_wallets_is_deleted ON wallets(is_deleted);