-- Flyway migration script V3: Add User entity and relationship with Wallet
-- Compatible with H2 and PostgreSQL

-- 1. Create users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE
);

-- 2. Add user_id column to wallets (nullable temporarily)
ALTER TABLE wallets ADD COLUMN user_id BIGINT;

-- 3. Create a default demo user (password: 'password' - will be encoded later)
INSERT INTO users (username, password, email, role, created_at, updated_at, is_deleted)
VALUES ('demo', 'password', 'demo@example.com', 'ROLE_USER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false);

-- 4. Assign existing wallets to the demo user
UPDATE wallets SET user_id = (SELECT id FROM users WHERE username = 'demo') WHERE user_id IS NULL;

-- 5. Now set user_id column to NOT NULL
ALTER TABLE wallets ALTER COLUMN user_id SET NOT NULL;

-- 6. Add foreign key constraint
ALTER TABLE wallets ADD CONSTRAINT fk_wallet_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- 7. Create indexes for performance
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_wallets_user_id ON wallets(user_id);